### ISSUE TITLE
Settings Issue

### ISSUE THREAD

**Issue by shaikhnedab** [steeven-th/pterodactyl-status-server-wordpress#1]
I am getting following error while settings up API credentials in wordpress.

```An error of type E_ERROR was caused in line 114 of the file
/var/www/html/wp-content/plugins/pteroq-server-status/admin/templates/api_setup.php.
Error message: Uncaught Error: Call to undefined function
display_errors() in
/var/www/html/wp-content/plugins/pteroq-server-status/admin/templates/api_setup.php:114
Stack trace:
#0 /var/www/html/wp-content/plugins/pteroq-server-status/includes/settings.php(28):
include()
#1 /var/www/html/wp-includes/class-wp-hook.php(303): sthomas_pteroq_settings()
#2 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#3 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action()
#4 /var/www/html/wp-admin/admin.php(259): do_action()
#5 {main}
  thrown
```

```
WordPress version 5.8.2
Current theme: Hestia Pro (version 3.0.8)
Current plugin: Pterodactyl games servers status (version 1.0.1)
PHP version 7.4.26
```

**Comment by steeven-th** [comment]
Hello, I fixed the problem in the version 1.0.2 that I just put on Github. You can download it and replace your files, you should not have this error anymore.

**Comment by shaikhnedab** [comment]
hello, 
just update no longer getting that error still goto next step.
![image](https://user-images.githubusercontent.com/55206494/145684003-ef1fc0ad-3d44-4a38-ad94-4609ad63090f.png)
my panel runs on port 80 therefore I left last column empty.
fyi I am running my panel on subdomain if it helps.

**Comment by steeven-th** [comment]
Ok, can you test with the 1.0.3 update pls ?

**Comment by shaikhnedab** [comment]
settings section was successful. but after adding game server getting following error.
![image](https://user-images.githubusercontent.com/55206494/145685548-f5fc0b08-f5e2-42cc-9556-96e4c11552c7.png)
checked multiple times server id is correct.
My panel and game server(above id is for teamspeak3 server) running on same machine.

Edit: if you want I can give you temp access to my panel.

**Comment by steeven-th** [comment]
Your UUID is not correct. Look the README, take juste the first party of your UUID 606f2568

https://github.com/steeven-th/pterodactyl-status-server-wordpress/blob/master/images/uuid.png

**Comment by shaikhnedab** [comment]
still same.
![image](https://user-images.githubusercontent.com/55206494/145685772-4b37ed25-0e1d-4226-9f4f-acf36b27c31a.png)

**Comment by steeven-th** [comment]
Check your API key

**Comment by shaikhnedab** [comment]
well just recreated both API and still same error.

**Comment by steeven-th** [comment]
You have created two API keys (one in the back office and one in the front office) and assigned all permissions to READ on the back office API key?

**Comment by shaikhnedab** [comment]
yes one is server API key and other one is client API and gave all read permissions to server API key.

**Comment by steeven-th** [comment]
Can you give me your API KEY SERVER pls ? In private message
You found me on Discord Pterodactyl https://discord.com/invite/pterodactyl

**Comment by steeven-th** [comment]
Problem solved by replacing the IP with the domain name
